openapi: 3.0.0
info:
  title: URL Shortener API
  version: "1.0.0"
  description: API for creating and managing short URLs with analytics and Google authentication.
servers:
  - url: https://alteroffice-backend.vercel.app
paths:
  /auth/google:
    get:
      summary: Initiate Google OAuth login.
      responses:
        '302':
          description: Redirect to Google OAuth consent screen.
  /auth/google/callback:
    get:
      summary: Google OAuth callback.
      responses:
        '302':
          description: Redirect to frontend after successful authentication.
  /api/shorten:
    post:
      summary: Create a new short URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  example: "https://example.com/very-long-url"
                customAlias:
                  type: string
                  example: "myalias"
                topic:
                  type: string
                  example: "coding"
      responses:
        '200':
          description: Short URL created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: "https://alteroffice-backend.vercel.app/myalias"
                  createdAt:
                    type: string
                    format: date-time
        '400':
          description: Error (e.g. alias already exists).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alias already in use."
  /api/shorten/{alias}:
    get:
      summary: Redirect to the original URL.
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to the long URL.
        '404':
          description: URL not found.
  /api/analytics/{alias}:
    get:
      summary: Retrieve analytics for a specific short URL or overall if alias is 'overall'.
      parameters:
        - in: path
          name: alias
          required: true
          schema:
            type: string
          description: "The short URL alias or 'overall' for overall analytics."
      responses:
        '200':
          description: Analytics data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalClicks:
                    type: number
                    example: 10
                  uniqueUsers:
                    type: number
                    example: 5
                  clicksByDate:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          example: "2025-02-11"
                        clickCount:
                          type: number
                          example: 3
                  osType:
                    type: array
                    items:
                      type: object
                      properties:
                        osName:
                          type: string
                          example: "Windows"
                        uniqueClicks:
                          type: number
                          example: 4
                        uniqueUsers:
                          type: number
                          example: 2
                  deviceType:
                    type: array
                    items:
                      type: object
                      properties:
                        deviceName:
                          type: string
                          example: "desktop"
                        uniqueClicks:
                          type: number
                          example: 6
                        uniqueUsers:
                          type: number
                          example: 3
        '404':
          description: URL not found.
  /api/analytics/topic/{topic}:
    get:
      summary: Retrieve analytics for all URLs under a specific topic.
      parameters:
        - in: path
          name: topic
          required: true
          schema:
            type: string
          description: "The topic name (e.g., coding)."
      responses:
        '200':
          description: Topic analytics data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalClicks:
                    type: number
                    example: 20
                  uniqueUsers:
                    type: number
                    example: 10
                  clicksByDate:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          example: "2025-02-11"
                        clickCount:
                          type: number
                          example: 5
                  urls:
                    type: array
                    items:
                      type: object
                      properties:
                        shortUrl:
                          type: string
                          example: "https://alteroffice-backend.vercel.app/myalias"
                        totalClicks:
                          type: number
                          example: 10
                        uniqueUsers:
                          type: number
                          example: 4
        '404':
          description: No URLs found for this topic.
components: {}
